var ff = {
    "Scope": {
        "IsConnected": true,
        "Options": {
            "Locale": "",
            "Username": null,
            "Authority": "",
            "Impersonation": 3,
            "Authentication": -1,
            "EnablePrivileges": false,
            "Context": [],
            "Timeout": {
                "Ticks": 9223372036854775807,
                "Days": 10675199,
                "Hours": 2,
                "Milliseconds": 477,
                "Minutes": 48,
                "Seconds": 5,
                "TotalDays": 10675199.116730064,
                "TotalHours": 256204778.80152154,
                "TotalMilliseconds": 922337203685477,
                "TotalMinutes": 15372286728.091293,
                "TotalSeconds": 922337203685.47754
            }
        },
        "Path": {
            "Path": "\\\\.\\root\\cimv2",
            "RelativePath": "",
            "Server": ".",
            "NamespacePath": "root\\cimv2",
            "ClassName": "",
            "IsClass": false,
            "IsInstance": false,
            "IsSingleton": false
        }
    },
    "Path": {
        "Path": "\\\\BULUSLI-PC\\root\\cimv2:Win32_NetworkAdapterConfiguration.Index=3",
        "RelativePath": "Win32_NetworkAdapterConfiguration.Index=3",
        "Server": "BULUSLI-PC",
        "NamespacePath": "root\\cimv2",
        "ClassName": "Win32_NetworkAdapterConfiguration",
        "IsClass": false,
        "IsInstance": true,
        "IsSingleton": false
    },
    "Options": {
        "UseAmendedQualifiers": false,
        "Context": [],
        "Timeout": {
            "Ticks": 9223372036854775807,
            "Days": 10675199,
            "Hours": 2,
            "Milliseconds": 477,
            "Minutes": 48,
            "Seconds": 5,
            "TotalDays": 10675199.116730064,
            "TotalHours": 256204778.80152154,
            "TotalMilliseconds": 922337203685477,
            "TotalMinutes": 15372286728.091293,
            "TotalSeconds": 922337203685.47754
        }
    },
    "ClassPath": {
        "Path": "\\\\BULUSLI-PC\\root\\cimv2:Win32_NetworkAdapterConfiguration",
        "RelativePath": "Win32_NetworkAdapterConfiguration",
        "Server": "BULUSLI-PC",
        "NamespacePath": "root\\cimv2",
        "ClassName": "Win32_NetworkAdapterConfiguration",
        "IsClass": true,
        "IsInstance": false,
        "IsSingleton": false
    },
    "Properties": [{
        "Name": "ArpAlwaysSourceRoute",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "ArpUseEtherSNAP",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "Caption",
        "Value": "[00000003] Realtek PCIe GBE Family Controller",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "CIM_Setting",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DatabasePath",
        "Value": "%SystemRoot%\\System32\\drivers\\etc",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DeadGWDetectEnabled",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DefaultIPGateway",
        "Value": ["172.18.190.254"],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DefaultTOS",
        "Value": null,
        "Type": 17,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint8",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DefaultTTL",
        "Value": 64,
        "Type": 17,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint8",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "Description",
        "Value": "Realtek PCIe GBE Family Controller",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "CIM_Setting",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DHCPEnabled",
        "Value": false,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DHCPLeaseExpires",
        "Value": null,
        "Type": 101,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "datetime",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DHCPLeaseObtained",
        "Value": null,
        "Type": 101,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "datetime",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DHCPServer",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DNSDomain",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DNSDomainSuffixSearchOrder",
        "Value": [],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DNSEnabledForWINSResolution",
        "Value": false,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DNSHostName",
        "Value": "bulusli-PC",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DNSServerSearchOrder",
        "Value": ["202.106.196.115", "219.141.136.10"],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "DomainDNSRegistrationEnabled",
        "Value": false,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "ForwardBufferMemory",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "FullDNSRegistrationEnabled",
        "Value": true,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "GatewayCostMetric",
        "Value": [256],
        "Type": 18,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint16",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IGMPLevel",
        "Value": null,
        "Type": 17,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint8",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "Index",
        "Value": 3,
        "Type": 19,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }, {
            "Name": "key",
            "Value": true,
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": false
        }]
    }, {
        "Name": "InterfaceIndex",
        "Value": 28,
        "Type": 19,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPAddress",
        "Value": ["172.18.190.211", "fe80::61a9:f092:fa81:6e5f"],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPConnectionMetric",
        "Value": 10,
        "Type": 19,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPEnabled",
        "Value": true,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPFilterSecurityEnabled",
        "Value": false,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPPortSecurityEnabled",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPSecPermitIPProtocols",
        "Value": [],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPSecPermitTCPPorts",
        "Value": [],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPSecPermitUDPPorts",
        "Value": [],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPSubnet",
        "Value": ["255.255.255.0", "64"],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPUseZeroBroadcast",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPXAddress",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPXEnabled",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPXFrameType",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPXMediaType",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPXNetworkNumber",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": true,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "IPXVirtualNetNumber",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "KeepAliveInterval",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "KeepAliveTime",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "MACAddress",
        "Value": "E0:DB:55:9E:A7:4B",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "MTU",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "NumForwardPackets",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "PMTUBHDetectEnabled",
        "Value": true,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "PMTUDiscoveryEnabled",
        "Value": true,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "ServiceName",
        "Value": "rt640x64",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "SettingID",
        "Value": "{FE5F2D99-219A-4FA9-93F8-A1A8DB2F375F}",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "CIM_Setting",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "TcpipNetbiosOptions",
        "Value": 0,
        "Type": 19,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "TcpMaxConnectRetransmissions",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "TcpMaxDataRetransmissions",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "TcpNumConnections",
        "Value": null,
        "Type": 19,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint32",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "TcpUseRFC1122UrgentPointer",
        "Value": null,
        "Type": 11,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "TcpWindowSize",
        "Value": null,
        "Type": 18,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "uint16",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "WINSEnableLMHostsLookup",
        "Value": true,
        "Type": 11,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "boolean",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "WINSHostLookupFile",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "WINSPrimaryServer",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "WINSScopeID",
        "Value": "",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }, {
        "Name": "WINSSecondaryServer",
        "Value": null,
        "Type": 8,
        "IsLocal": false,
        "IsArray": false,
        "Origin": "Win32_NetworkAdapterConfiguration",
        "Qualifiers": [{
            "Name": "CIMTYPE",
            "Value": "string",
            "IsAmended": false,
            "IsLocal": false,
            "PropagatesToInstance": true,
            "PropagatesToSubclass": true,
            "IsOverridable": true
        }]
    }],
    "SystemProperties": [{
        "Name": "__GENUS",
        "Value": 2,
        "Type": 3,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__CLASS",
        "Value": "Win32_NetworkAdapterConfiguration",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__SUPERCLASS",
        "Value": "CIM_Setting",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__DYNASTY",
        "Value": "CIM_Setting",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__RELPATH",
        "Value": "Win32_NetworkAdapterConfiguration.Index=3",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__PROPERTY_COUNT",
        "Value": 61,
        "Type": 3,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__DERIVATION",
        "Value": ["CIM_Setting"],
        "Type": 8,
        "IsLocal": true,
        "IsArray": true,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__SERVER",
        "Value": "BULUSLI-PC",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__NAMESPACE",
        "Value": "root\\cimv2",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }, {
        "Name": "__PATH",
        "Value": "\\\\BULUSLI-PC\\root\\cimv2:Win32_NetworkAdapterConfiguration.Index=3",
        "Type": 8,
        "IsLocal": true,
        "IsArray": false,
        "Origin": "___SYSTEM",
        "Qualifiers": []
    }],
    "Qualifiers": [{
        "Name": "dynamic",
        "Value": true,
        "IsAmended": false,
        "IsLocal": false,
        "PropagatesToInstance": true,
        "PropagatesToSubclass": false,
        "IsOverridable": true
    }, {
        "Name": "Locale",
        "Value": 1033,
        "IsAmended": false,
        "IsLocal": false,
        "PropagatesToInstance": true,
        "PropagatesToSubclass": false,
        "IsOverridable": true
    }, {
        "Name": "provider",
        "Value": "CIMWin32",
        "IsAmended": false,
        "IsLocal": false,
        "PropagatesToInstance": true,
        "PropagatesToSubclass": false,
        "IsOverridable": true
    }, {
        "Name": "UUID",
        "Value": "{8502C515-5FBB-11D2-AAC1-006008C78BC7}",
        "IsAmended": false,
        "IsLocal": false,
        "PropagatesToInstance": true,
        "PropagatesToSubclass": false,
        "IsOverridable": true
    }],
    "Site": null,
    "Container": null
}